import { describe, expect, it } from "vitest";
import { colorPalettes } from "@/data/colors";

// This test is driven by my παράνοια and designed this way to make me calm and happy, even if I have to spend one hour copy-pasting all the changes :)
const expectedDefaultPaletteHexes = {
  COLOR_LIMESTONE: { hex: "#c6b5ab", secondaryColor: "#958675" },
  COLOR_IRON_ORE: { hex: "#656f8c", secondaryColor: "#663633" },
  COLOR_COPPER_ORE: { hex: "#9d5a47", secondaryColor: "#405a61" },
  COLOR_CATERIUM_ORE: { hex: "#e9d2a0", secondaryColor: "#a27a40" },
  COLOR_COAL: { hex: "#050807", secondaryColor: "#0b0f15" },
  COLOR_RAW_QUARTZ: { hex: "#e7a5d6", secondaryColor: "#c652c6" },
  COLOR_SULFUR: { hex: "#ffef63", secondaryColor: "#86762c" },
  COLOR_BAUXITE: { hex: "#d29a80", secondaryColor: "#9c5548" },
  COLOR_SAM: { hex: "#713db2", secondaryColor: "#502784" },
  COLOR_URANIUM: { hex: "#448a3a", secondaryColor: "#173717" },
  COLOR_IRON_INGOT: { hex: "#8e9298", secondaryColor: "#484948" },
  COLOR_COPPER_INGOT: { hex: "#b07e7c", secondaryColor: "#553329" },
  COLOR_CATERIUM_INGOT: { hex: "#cdba89", secondaryColor: "#927844" },
  COLOR_STEEL_INGOT: { hex: "#23272c", secondaryColor: "#0f1011" },
  COLOR_ALUMINUM_INGOT: { hex: "#cccdcf", secondaryColor: "#696969" },
  COLOR_FICSITE_INGOT: { hex: "#ea7d04", secondaryColor: "#5a1f00" },
  COLOR_CONCRETE: { hex: "#83755f", secondaryColor: "#c7c3c8" },
  COLOR_QUARTZ_CRYSTAL: { hex: "#eea2ed", secondaryColor: "#2941c7" },
  COLOR_SILICA: { hex: "#dcdce8", secondaryColor: "#b4d5e4" },
  COLOR_COPPER_POWDER: { hex: "#7f5664", secondaryColor: "#d6d8e7" },
  COLOR_POLYMER_RESIN: { hex: "#252fd4", secondaryColor: "#060330" },
  COLOR_PETROLEUM_COKE: { hex: "#2b2c34", secondaryColor: "#060606" },
  COLOR_ALUMINUM_SCRAP: { hex: "#cccdcf", secondaryColor: "#d48f28" },
  COLOR_ALIEN_PROTEIN: { hex: "#654368", secondaryColor: "#c9cbce" },
  COLOR_ALIEN_DNA_CAPSULE: { hex: "#96949d", secondaryColor: "#49343c" },
  COLOR_WATER: { hex: "#7ab0d4", secondaryColor: "#0d0d0d" },
  COLOR_CRUDE_OIL: { hex: "#190019", secondaryColor: "#0d0d0d" },
  COLOR_HEAVY_OIL_RESIDUE: { hex: "#6d2d78", secondaryColor: "#0d0d0d" },
  COLOR_FUEL: { hex: "#eb7d15", secondaryColor: "#0d0d0d" },
  COLOR_LIQUID_BIOFUEL: { hex: "#3b532c", secondaryColor: "#0d0d0d" },
  COLOR_TURBOFUEL: { hex: "#d4292e", secondaryColor: "#0d0d0d" },
  COLOR_ALUMINA_SOLUTION: { hex: "#c1c1c1", secondaryColor: "#0d0d0d" },
  COLOR_SULFURIC_ACID: { hex: "#ffff00", secondaryColor: "#0d0d0d" },
  COLOR_NITRIC_ACID: { hex: "#d9d9a2", secondaryColor: "#0d0d0d" },
  COLOR_DISSOLVED_SILICA: { hex: "#e2beee", secondaryColor: "#0d0d0d" },
  COLOR_NITROGEN_GAS: { hex: "#595959", secondaryColor: "#0d0d0d" },
  COLOR_ROCKET_FUEL: { hex: "#bd251a", secondaryColor: "#0d0d0d" },
  COLOR_IONIZED_FUEL: { hex: "#d55f1a", secondaryColor: "#0d0d0d" },
  COLOR_DARK_MATTER_RESIDUE: { hex: "#fdaff9", secondaryColor: "#0d0d0d" },
  COLOR_EXCITED_PHOTONIC_MATTER: { hex: "#76f5e8", secondaryColor: "#0d0d0d" },
  COLOR_IRON_ROD: { hex: "#595b63", secondaryColor: "#1c1e22" },
  COLOR_SCREWS: { hex: "#99a2aa", secondaryColor: "#1164ce" },
  COLOR_IRON_PLATE: { hex: "#afb2b6", secondaryColor: "#4c4f54" },
  COLOR_REINFORCED_IRON_PLATE: { hex: "#9aa2b5", secondaryColor: "#59657e" },
  COLOR_COPPER_SHEET: { hex: "#a1663e", secondaryColor: "#325a8d" },
  COLOR_ALCLAD_ALUMINUM_SHEET: { hex: "#cccdcf", secondaryColor: "#8d8f9e" },
  COLOR_ALUMINUM_CASING: { hex: "#cccdcf", secondaryColor: "#242526" },
  COLOR_STEEL_PIPE: { hex: "#323232", secondaryColor: "#703d30" },
  COLOR_STEEL_BEAM: { hex: "#292a2e", secondaryColor: "#703d30" },
  COLOR_ENCASED_INDUSTRIAL_BEAM: { hex: "#f4e9c5", secondaryColor: "#a55a5a" },
  COLOR_MODULAR_FRAME: { hex: "#838baa", secondaryColor: "#5d5d5d" },
  COLOR_HEAVY_MODULAR_FRAME: { hex: "#818896", secondaryColor: "#1b1b1b" },
  COLOR_FUSED_MODULAR_FRAME: { hex: "#b0b7ca", secondaryColor: "#fab757" },
  COLOR_FICSITE_TRIGON: { hex: "#fdb61e", secondaryColor: "#b64c00" },
  COLOR_FABRIC: { hex: "#978a85", secondaryColor: "#000003" },
  COLOR_PLASTIC: { hex: "#4eadf1", secondaryColor: "#221f24" },
  COLOR_RUBBER: { hex: "#1e1e1e", secondaryColor: "#cfb65e" },
  COLOR_ROTOR: { hex: "#364364", secondaryColor: "#744029" },
  COLOR_STATOR: { hex: "#5a5a5a", secondaryColor: "#633d31" },
  COLOR_BATTERY: { hex: "#2d3248", secondaryColor: "#aaadbc" },
  COLOR_MOTOR: { hex: "#596586", secondaryColor: "#cead1f" },
  COLOR_HEAT_SINK: { hex: "#cccdcf", secondaryColor: "#a1663e" },
  COLOR_COOLING_SYSTEM: { hex: "#df9d60", secondaryColor: "#d4d6e5" },
  COLOR_TURBO_MOTOR: { hex: "#151a16", secondaryColor: "#f4d24d" },
  COLOR_WIRE: { hex: "#ab6c47", secondaryColor: "#846b4f" },
  COLOR_CABLE: { hex: "#282a32", secondaryColor: "#94a5c6" },
  COLOR_QUICKWIRE: { hex: "#cdba89", secondaryColor: "#2a2e3f" },
  COLOR_CIRCUIT_BOARD: { hex: "#4b8052", secondaryColor: "#ffb85f" },
  COLOR_AI_LIMITER: { hex: "#1c1c1c", secondaryColor: "#88b6b3" },
  COLOR_HIGH_SPEED_CONNECTOR: { hex: "#4b8052", secondaryColor: "#415355" },
  COLOR_REANIMATED_SAM: { hex: "#8c3dcc", secondaryColor: "#e7904b" },
  COLOR_SAM_FLUCTUATOR: { hex: "#bd60d3", secondaryColor: "#ffab42" },
  COLOR_COMPUTER: { hex: "#c08e5a", secondaryColor: "#2e3531" },
  COLOR_SUPERCOMPUTER: { hex: "#1f1f1f", secondaryColor: "#e7b779" },
  COLOR_RADIO_CONTROL_UNIT: { hex: "#2b2b2b", secondaryColor: "#f7e650" },
  COLOR_CRYSTAL_OSCILLATOR: { hex: "#999999", secondaryColor: "#f7cf4e" },
  COLOR_SUPERPOSITION_OSCILLATOR: { hex: "#e8e0dd", secondaryColor: "#ea8e1f" },
  COLOR_DIAMONDS: { hex: "#e1d8dd", secondaryColor: "#da7821" },
  COLOR_TIME_CRYSTAL: { hex: "#e1d8dd", secondaryColor: "#da7821" },
  COLOR_DARK_MATTER_CRYSTAL: { hex: "#7305c6", secondaryColor: "#33375c" },
  COLOR_SINGULARITY_CELL: { hex: "#bbb8c3", secondaryColor: "#ffbd67" },
  COLOR_NEURAL_QUANTUM_PROCESSOR: { hex: "#4b3a88", secondaryColor: "#ea8e1f" },
  COLOR_ALIEN_POWER_MATRIX: { hex: "#d1ccd2", secondaryColor: "#ffeefe" },
  COLOR_EMPTY_CANISTER: { hex: "#63606a", secondaryColor: "#10100e" },
  COLOR_EMPTY_FLUID_TANK: { hex: "#7b95bd", secondaryColor: "#99969b" },
  COLOR_PRESSURE_CONVERSION_CUBE: { hex: "#d79c62", secondaryColor: "#1f2133" },
  COLOR_PACKAGED_WATER: { hex: "#7ab0d4", secondaryColor: "#0251b8" },
  COLOR_PACKAGED_ALUMINA_SOLUTION: {
    hex: "#d2d2dc",
    secondaryColor: "#fbce79",
  },
  COLOR_PACKAGED_SULFURIC_ACID: { hex: "#d9d665", secondaryColor: "#55585f" },
  COLOR_PACKAGED_NITRIC_ACID: { hex: "#dedede", secondaryColor: "#55585f" },
  COLOR_PACKAGED_NITROGEN_GAS: { hex: "#e2e1e7", secondaryColor: "#26273b" },
  COLOR_LEAVES: { hex: "#4d6f43", secondaryColor: "#142c12" },
  COLOR_MYCELIA: { hex: "#8b8186", secondaryColor: "#3e3c49" },
  COLOR_FLOWER_PETALS: { hex: "#a25544", secondaryColor: "#a25544" },
  COLOR_WOOD: { hex: "#735e43", secondaryColor: "#2a1e14" },
  COLOR_BIOMASS: { hex: "#6b5f35", secondaryColor: "#3e3118" },
  COLOR_COMPACTED_COAL: { hex: "#171a24", secondaryColor: "#0d0c0b" },
  COLOR_PACKAGED_OIL: { hex: "#0d0d0d", secondaryColor: "#f2f4f1" },
  COLOR_PACKAGED_HEAVY_OIL_RESIDUE: {
    hex: "#6d2d78",
    secondaryColor: "#f2f4f1",
  },
  COLOR_SOLID_BIOFUEL: { hex: "#847161", secondaryColor: "#3c2f25" },
  COLOR_PACKAGED_FUEL: { hex: "#f89900", secondaryColor: "#10100e" },
  COLOR_PACKAGED_LIQUID_BIOFUEL: { hex: "#4c762c", secondaryColor: "#10100e" },
  COLOR_PACKAGED_TURBOFUEL: { hex: "#e3101f", secondaryColor: "#10100e" },
  COLOR_PACKAGED_ROCKET_FUEL: { hex: "#ec0414", secondaryColor: "#feeb23" },
  COLOR_PACKAGED_IONIZED_FUEL: { hex: "#ce070e", secondaryColor: "#ffbd20" },
  COLOR_URANIUM_FUEL_ROD: { hex: "#189442", secondaryColor: "#a4f6c6" },
  COLOR_PLUTONIUM_FUEL_ROD: { hex: "#eced37", secondaryColor: "#a8e5e9" },
  COLOR_BLACK_POWDER: { hex: "#343434", secondaryColor: "#f10907" },
  COLOR_SMOKELESS_POWDER: { hex: "#0c0c0c", secondaryColor: "#f10907" },
  COLOR_GAS_FILTER: { hex: "#8e8aa1", secondaryColor: "#8e8aa1" },
  COLOR_COLOR_CARTRIDGE: { hex: "#9f6053", secondaryColor: "#9f6053" },
  COLOR_BEACON: { hex: "#917353", secondaryColor: "#917353" },
  COLOR_IODINE_INFUSED_FILTER: { hex: "#e3ba51", secondaryColor: "#e3ba51" },
  COLOR_IRON_REBAR: { hex: "#f39f25", secondaryColor: "#f39f25" },
  COLOR_STUN_REBAR: { hex: "#28b6da", secondaryColor: "#28b6da" },
  COLOR_SHATTER_REBAR: { hex: "#8e3d89", secondaryColor: "#8e3d89" },
  COLOR_EXPLOSIVE_REBAR: { hex: "#e32531", secondaryColor: "#e32531" },
  COLOR_RIFLE_AMMO: { hex: "#cc6927", secondaryColor: "#cc6927" },
  COLOR_HOMING_RIFLE_AMMO: { hex: "#272a2d", secondaryColor: "#272a2d" },
  COLOR_TURBO_RIFLE_AMMO: { hex: "#c12b31", secondaryColor: "#c12b31" },
  COLOR_NOBELISK: { hex: "#901400", secondaryColor: "#901400" },
  COLOR_GAS_NOBELISK: { hex: "#4f6f27", secondaryColor: "#4f6f27" },
  COLOR_PULSE_NOBELISK: { hex: "#7e9eaa", secondaryColor: "#7e9eaa" },
  COLOR_CLUSTER_NOBELISK: { hex: "#cc7c00", secondaryColor: "#cc7c00" },
  COLOR_NUKE_NOBELISK: { hex: "#dac500", secondaryColor: "#dac500" },
  COLOR_ELECTROMAGNETIC_CONTROL_ROD: {
    hex: "#586f9b",
    secondaryColor: "#ecec4e",
  },
  COLOR_ENCASED_URANIUM_CELL: { hex: "#eced37", secondaryColor: "#8bead0" },
  COLOR_NON_FISSILE_URANIUM: { hex: "#eced37", secondaryColor: "#bbffca" },
  COLOR_PLUTONIUM_PELLET: { hex: "#7e7765", secondaryColor: "#80d2e7" },
  COLOR_ENCASED_PLUTONIUM_CELL: { hex: "#2b3230", secondaryColor: "#a8e5e9" },
  COLOR_FICSONIUM: { hex: "#fff444", secondaryColor: "#988faa" },
  COLOR_FICSONIUM_FUEL_ROD: { hex: "#fff444", secondaryColor: "#ffe62a" },
  COLOR_URANIUM_WASTE: { hex: "#6ceb6c", secondaryColor: "#1ced3b" },
  COLOR_PLUTONIUM_WASTE: { hex: "#7ccee7", secondaryColor: "#7cd2e9" },
  COLOR_BLUE_POWER_SLUG: { hex: "#7bbfdd", secondaryColor: "#6b74ad" },
  COLOR_YELLOW_POWER_SLUG: { hex: "#e7b55a", secondaryColor: "#e79763" },
  COLOR_PURPLE_POWER_SLUG: { hex: "#df88e5", secondaryColor: "#b250d0" },
  COLOR_POWER_SHARD: { hex: "#fa9649", secondaryColor: "#6bbdde" },
  COLOR_FICSIT_COUPON: { hex: "#e49246", secondaryColor: "#e9a86a" },
  COLOR_SMART_PLATING: { hex: "#53597d", secondaryColor: "#b04a3e" },
  COLOR_VERSATILE_FRAMEWORK: { hex: "#17181c", secondaryColor: "#9f3329" },
  COLOR_AUTOMATED_WIRING: { hex: "#303030", secondaryColor: "#a8422e" },
  COLOR_MODULAR_ENGINE: { hex: "#433e45", secondaryColor: "#b94133" },
  COLOR_ADAPTIVE_CONTROL_UNIT: { hex: "#2e2c31", secondaryColor: "#e4a258" },
  COLOR_ASSEMBLY_DIRECTOR_SYSTEM: { hex: "#292b2e", secondaryColor: "#ad513a" },
  COLOR_MAGNETIC_FIELD_GENERATOR: { hex: "#303030", secondaryColor: "#7af0f0" },
  COLOR_THERMAL_PROPULSION_ROCKET: {
    hex: "#303030",
    secondaryColor: "#ae4a39",
  },
  COLOR_NUCLEAR_PASTA: { hex: "#ecbc8e", secondaryColor: "#7af0f0" },
  COLOR_BIOCHEMICAL_SCULPTOR: { hex: "#413853", secondaryColor: "#e95e49" },
  COLOR_BALLISTIC_WARP_DRIVE: { hex: "#27212d", secondaryColor: "#c83f1f" },
  COLOR_AI_EXPANSION_SERVER: { hex: "#dcd4d2", secondaryColor: "#c54017" },
  LIGHT_CANDLE: { hex: "#FF9329", secondaryColor: "#000000" },
  LIGHT_40W_TUNGSTEN: { hex: "#FFC58F", secondaryColor: "#000000" },
  LIGHT_100W_TUNGSTEN: { hex: "#FFD6AA", secondaryColor: "#000000" },
  LIGHT_HALOGEN: { hex: "#FFF1E0", secondaryColor: "#000000" },
  LIGHT_CARBON_ARC: { hex: "#FFFAF4", secondaryColor: "#000000" },
  LIGHT_HIGH_NOON_SUN: { hex: "#FFFFFB", secondaryColor: "#000000" },
  LIGHT_DIRECT_SUNLIGHT: { hex: "#FFFFFF", secondaryColor: "#000000" },
  LIGHT_OVERCAST_SKY: { hex: "#C9E1FF", secondaryColor: "#000000" },
  LIGHT_CLEAR_BLUE_SKY: { hex: "#409CFF", secondaryColor: "#000000" },
  LIGHT_WARM_FLUORESCENT: { hex: "#FFF4E5", secondaryColor: "#000000" },
  LIGHT_STANDARD_FLUORESCENT: { hex: "#F4FFFA", secondaryColor: "#000000" },
  LIGHT_COOL_WHITE_FLUORESCENT: { hex: "#D4F5FF", secondaryColor: "#000000" },
  LIGHT_FULL_SPECTRUM_FLUORESCENT: {
    hex: "#FFF4F2",
    secondaryColor: "#000000",
  },
  LIGHT_GROW_LIGHT_FLUORESCENT: { hex: "#FFF9F7", secondaryColor: "#000000" },
  LIGHT_BLACK_LIGHT_FLUORESCENT: { hex: "#A700FF", secondaryColor: "#000000" },
  LIGHT_MERCURY_VAPOR: { hex: "#D8F7FF", secondaryColor: "#000000" },
  LIGHT_SODIUM_VAPOR: { hex: "#FFD1B2", secondaryColor: "#000000" },
  LIGHT_METAL_HALIDE: { hex: "#F2FCFF", secondaryColor: "#000000" },
  LIGHT_HIGH_PRESSURE_SODIUM: { hex: "#FFB84C", secondaryColor: "#000000" },
} as const;

describe("default palette hex integrity", () => {
  it("matches the locked expected hex values", () => {
    const actual = Object.fromEntries(
      colorPalettes.default.colorRecords.map((color) => [
        color.code,
        { hex: color.hex, secondaryColor: color.secondaryColor },
      ]),
    );

    expect(actual).toEqual(expectedDefaultPaletteHexes);
  });
});
